name: honegumi
channels:
  - defaults
  - conda-forge
  # - pytorch
dependencies:
  - python >=3.6,<3.12
  - pip
  - ipython
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - pandoc
  - matplotlib
  - pip:
     - -e .[ax,dev]  # install git checkout of honegumi in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  # - jupyterlab
  - pytest
  - pytest-cov
  - tox
  # - pre_commit # causes issues with conda! (e.g., pre-commit autoupdate)
  # - nbdime
  # - nbstripout
  - sphinx
  - recommonmark
